import { useEffect, useState } from 'react';

const emptyForm = { name: '', email: '', role: 'receptionist', password: '', confirmPassword: '', doctor: '', active: true };
function UserForm({ user, doctors, onSubmit, saving, error }) {
  const [form, setForm] = useState(emptyForm); const editing = Boolean(user);
  useEffect(() => { setForm(user ? { ...emptyForm, name: user.name || '', email: user.email || '', role: user.role || 'receptionist', doctor: user.doctor?.id || '', active: user.active !== false } : emptyForm); }, [user]);
  const update = (event) => { const { name, value, type, checked } = event.target; setForm((current) => ({ ...current, [name]: type === 'checkbox' ? checked : value, ...(name === 'role' && value !== 'doctor' ? { doctor: '' } : {}) })); };
  const submit = (event) => { event.preventDefault(); if (!form.name.trim() || !form.email.trim()) return onSubmit(null, 'Name and email are required.'); if (!editing && form.password.length < 8) return onSubmit(null, 'Password must be at least 8 characters.'); if (form.password && form.password.length < 8) return onSubmit(null, 'New password must be at least 8 characters.'); if (form.password !== form.confirmPassword) return onSubmit(null, 'Passwords do not match.'); if (form.role === 'doctor' && !form.doctor) return onSubmit(null, 'A Doctor profile is required for doctor users.'); const payload = { name: form.name.trim(), email: form.email.trim(), role: form.role, active: form.active }; if (form.role === 'doctor') payload.doctor = form.doctor; if (form.password) payload.password = form.password; onSubmit(payload); };
  return <form className="user-form" onSubmit={submit}><div className="user-form-grid"><label>Name <span>*</span><input name="name" value={form.name} onChange={update} required /></label><label>Email <span>*</span><input name="email" type="email" value={form.email} onChange={update} required /></label><label>Role <span>*</span><select name="role" value={form.role} onChange={update}><option value="admin">Admin</option><option value="doctor">Doctor</option><option value="receptionist">Receptionist</option></select></label>{form.role === 'doctor' && <label>Doctor profile <span>*</span><select name="doctor" value={form.doctor} onChange={update} required><option value="">Select Doctor</option>{doctors.map((doctor) => <option key={doctor._id} value={doctor._id}>{doctor.name}{doctor.specialization ? ` · ${doctor.specialization}` : ''}</option>)}</select></label>}<label>Password {!editing && <span>*</span>}<input name="password" type="password" minLength="8" autoComplete="new-password" value={form.password} onChange={update} placeholder={editing ? 'Leave blank to keep current password' : ''} required={!editing} /></label><label>Confirm Password {!editing && <span>*</span>}<input name="confirmPassword" type="password" minLength="8" autoComplete="new-password" value={form.confirmPassword} onChange={update} required={!editing} /></label></div>{editing && <label className="user-active-toggle"><input name="active" type="checkbox" checked={form.active} onChange={update} /> Account is active</label>}{error && <p className="user-form-error" role="alert">{error}</p>}<button className="users-primary-action" type="submit" disabled={saving}>{saving ? 'Saving account…' : editing ? 'Update User' : 'Create User'}</button></form>;
}

export default UserForm;
