import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import DashboardLayout from '../components/dashboard/DashboardLayout';
import UserModal from '../components/users/UserModal';
import UserTable from '../components/users/UserTable';
import { useAuth } from '../context/AuthContext';
import api from '../lib/api';
import './UsersPage.css';

const collection = (response) => Array.isArray(response.data?.data) ? response.data.data : [];
const message = (error, fallback) => error.response?.data?.message || fallback;

function UsersPage() {
  const { user } = useAuth(); const isAdmin = user?.role === 'admin'; const [users, setUsers] = useState([]); const [doctors, setDoctors] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [success, setSuccess] = useState(''); const [search, setSearch] = useState(''); const [role, setRole] = useState(''); const [status, setStatus] = useState(''); const [linked, setLinked] = useState(''); const [editing, setEditing] = useState(undefined); const [saving, setSaving] = useState(false); const [formError, setFormError] = useState(''); const [togglingId, setTogglingId] = useState(null); const fetched = useRef(false);
  const loadData = useCallback(async () => { setLoading(true); setError(''); try { const [usersResponse, doctorsResponse] = await Promise.all([api.get('/users'), api.get('/doctors')]); setUsers(collection(usersResponse)); setDoctors(collection(doctorsResponse)); } catch (requestError) { setError(message(requestError, 'User management data could not be loaded. Please try again.')); } finally { setLoading(false); } }, []);
  useEffect(() => { if (isAdmin && !fetched.current) { fetched.current = true; loadData(); } }, [isAdmin, loadData]);
  const filtered = useMemo(() => { const query = search.trim().toLowerCase(); return users.filter((item) => (!query || [item.name, item.email].some((value) => String(value || '').toLowerCase().includes(query))) && (!role || item.role === role) && (!status || (status === 'active' ? item.active !== false : item.active === false)) && (!linked || (linked === 'linked' ? Boolean(item.doctor) : !item.doctor))); }, [users, search, role, status, linked]);
  const saveUser = async (payload, validationError) => { if (validationError) { setFormError(validationError); return; } setSaving(true); setFormError(''); try { const response = editing ? await api.put(`/users/${editing.id || editing._id}`, payload) : await api.post('/users', payload); const saved = response.data?.data; setUsers((current) => editing ? current.map((item) => (item.id || item._id) === (saved.id || saved._id) ? saved : item) : [saved, ...current]); setEditing(undefined); setSuccess(editing ? 'User updated successfully.' : 'User created successfully.'); } catch (requestError) { setFormError(message(requestError, 'User could not be saved. Please check the details and try again.')); } finally { setSaving(false); } };
  const toggleUser = async (item) => { const id = item.id || item._id; const isActive = item.active !== false; if (isActive && !window.confirm(`Deactivate ${item.name}'s account? They will no longer be able to log in.`)) return; setTogglingId(id); setError(''); try { if (isActive) await api.delete(`/users/${id}`); else await api.put(`/users/${id}`, { active: true }); setUsers((current) => current.map((userItem) => (userItem.id || userItem._id) === id ? { ...userItem, active: !isActive } : userItem)); setSuccess(isActive ? 'User deactivated successfully.' : 'User activated successfully.'); } catch (requestError) { setError(message(requestError, 'User status could not be changed. Please try again.')); } finally { setTogglingId(null); } };
  if (!isAdmin) return <DashboardLayout activeItem="User Management" title="User Management"><div className="dashboard-content users-content"><section className="users-denied"><p className="section-label">Restricted workspace</p><h2>Permission required</h2><p>User Management is available to administrators only.</p></section></div></DashboardLayout>;
  const summary = { total: users.length, active: users.filter((item) => item.active !== false).length, doctors: users.filter((item) => item.role === 'doctor').length, receptionists: users.filter((item) => item.role === 'receptionist').length, admins: users.filter((item) => item.role === 'admin').length };
  return <DashboardLayout activeItem="User Management" title="User Management"><div className="dashboard-content users-content"><section className="users-page-heading"><div><p className="section-label">Staff access administration</p><h2>User Management</h2><p>Manage staff accounts, roles, access status, and Doctor profile associations.</p></div><button className="users-primary-action" type="button" onClick={() => { setFormError(''); setEditing(null); }}>+ Add User</button></section>{success && <p className="users-success" role="status">{success}</p>}{error && <div className="users-alert" role="alert"><span>{error}</span><button type="button" onClick={loadData}>Retry</button></div>}<section className="users-summary-grid"><article><span>Total Users</span><strong>{loading ? '—' : summary.total}</strong></article><article><span>Active Users</span><strong>{loading ? '—' : summary.active}</strong></article><article><span>Doctors</span><strong>{loading ? '—' : summary.doctors}</strong></article><article><span>Receptionists</span><strong>{loading ? '—' : summary.receptionists}</strong></article><article><span>Admins</span><strong>{loading ? '—' : summary.admins}</strong></article></section><section className="users-card"><div className="users-toolbar"><label className="users-search"><span aria-hidden="true">⌕</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search name or email" aria-label="Search users" /></label><select value={role} onChange={(event) => setRole(event.target.value)} aria-label="Filter by role"><option value="">All roles</option><option value="admin">Admins</option><option value="doctor">Doctors</option><option value="receptionist">Receptionists</option></select><select value={status} onChange={(event) => setStatus(event.target.value)} aria-label="Filter by status"><option value="">All statuses</option><option value="active">Active</option><option value="inactive">Inactive</option></select><select value={linked} onChange={(event) => setLinked(event.target.value)} aria-label="Filter by Doctor link"><option value="">All Doctor links</option><option value="linked">Linked</option><option value="unlinked">Not linked</option></select><span className="users-count">{loading ? 'Loading…' : `${filtered.length} user${filtered.length === 1 ? '' : 's'}`}</span></div><UserTable users={filtered} loading={loading} onEdit={(item) => { setFormError(''); setEditing(item); }} onToggle={toggleUser} togglingId={togglingId} /></section></div>{editing !== undefined && <UserModal user={editing} doctors={doctors} onClose={() => !saving && setEditing(undefined)} onSubmit={saveUser} saving={saving} error={formError} />}</DashboardLayout>;
}

export default UsersPage;
